# Generated by Django 3.1.14 on 2022-02-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='coding', max_length=200),
        ),
    ]
