# Generated by Django 3.1.14 on 2022-02-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20220225_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='', max_length=150),
        ),
    ]
