# Generated by Django 3.1.14 on 2022-02-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_auto_20220226_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
