# Generated by Django 3.1.14 on 2022-03-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_auto_20220227_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date',
            field=models.DateField(auto_now_add=True, default='2022-12-15'),
            preserve_default=False,
        ),
    ]
