# Generated by Django 3.1.14 on 2022-03-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0027_profilefeedback_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefeedback',
            name='like_count',
            field=models.BigIntegerField(default='0'),
        ),
    ]
