# Generated by Django 3.1.14 on 2022-03-12 15:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(choices=[('mr', 'Mr.'), ('ms', 'Ms.'), ('mrs', 'Mrs.'), ('dr.', 'Dr.'), ('prof', 'Prof.')], max_length=50, verbose_name='Mr. or Ms. ?')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=80)),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField(verbose_name="Transfer bo'yicha batafsil ma'lomot")),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
