# Generated by Django 3.1.14 on 2022-03-13 10:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Write your message...'),
        ),
    ]
