# Generated by Django 3.1.14 on 2022-02-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_transfer_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
