# Generated by Django 3.1.14 on 2022-02-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0004_transfer_operating_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='operating_system',
        ),
        migrations.AddField(
            model_name='transfer',
            name='pul_yuboriladigan_davlatni_tanlang',
            field=models.CharField(choices=[('uzb', "O'zbekistondan Germaniyaga"), ('ger', "Germaniyadan O'zbekistonga")], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='transfer_pul_birligini_tanlang',
            field=models.CharField(choices=[('dollar', 'faqat dollarda kerak'), ('som', 'faqat sömda kerak'), ('euro', 'faqat euroda kerak'), ('euroordollar', 'euro yoki dollarda kerak'), ('euroorsom', 'euro yoki sömda kerak'), ('sömordollar', 'dollar yoki sömda kerak')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='price',
            field=models.IntegerField(),
        ),
    ]
