# Generated by Django 3.1.14 on 2022-02-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0006_auto_20220222_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transfer_pul_birligini_tanlang',
            field=models.CharField(choices=[('dollar', 'faqat dollarda kerak'), ('som', 'faqat sömda kerak'), ('euro', 'faqat euroda kerak'), ('euroordollar', 'euro yoki dollarda kerak'), ('euroorsom', 'euro yoki sömda kerak'), ('somordollar', 'dollar yoki sömda kerak')], max_length=50),
        ),
    ]
