# Generated by Django 3.1.14 on 2022-02-22 08:41

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0007_auto_20220222_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='pul_yuboriladigan_davlatni_tanlang',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('UZB', "O'zbekistondan Germaniyaga"), ('GER', "Germaniyadan O'zbekistonga")], max_length=7),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_pul_birligini_tanlang',
            field=models.CharField(choices=[('dollar', 'faqat dollarda kerak'), ('som', 'faqat sömda kerak'), ('euro', 'faqat euroda kerak'), ('euroordollar', 'euro yoki dollarda kerak'), ('euroorsom', 'euro yoki sömda kerak'), ('somordollar', 'dollar yoki sömda kerak'), ('irrelevant', "farqi yo'q")], max_length=50),
        ),
    ]
