# Generated by Django 3.1.14 on 2022-02-22 09:40

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0008_auto_20220222_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='transfers_turi',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('fasttransfer', 'Echtzeit Überweisung'), ('plastik', 'Plastik karta'), ('cash', 'Naqd pul'), ('paypal', 'Paypal'), ('normaltransfer', 'Bank hisob raqamidan (2-3 ish kuni davom etadi)'), ('irrelevant', "farqi yo'q")], default=0, max_length=58),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='pul_yuboriladigan_davlatni_tanlang',
            field=models.CharField(choices=[('UZB', "O'zbekistondan Germaniyaga"), ('GER', "Germaniyadan O'zbekistonga")], max_length=100),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_pul_birligini_tanlang',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dollar', 'faqat dollarda kerak'), ('som', 'faqat sömda kerak'), ('euro', 'faqat euroda kerak'), ('euroordollar', 'euro yoki dollarda kerak'), ('euroorsom', 'euro yoki sömda kerak'), ('somordollar', 'dollar yoki sömda kerak'), ('irrelevant', "farqi yo'q")], max_length=50),
        ),
    ]
