# Generated by Django 3.1.14 on 2022-02-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0010_auto_20220222_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='qaysi_shahar_yoki_viloyat',
            field=models.CharField(choices=[('tashkent', 'Toshkent'), ('tashkent_city', 'Toshkent shahri'), ('valley', 'Vodiy'), ('samarqandandtashkent', 'Toshkent/Samarqand'), ('namangan', 'Namangan'), ('andijan', 'Andijon'), ('fergana', "Farg'ona"), ('guliston', 'Guliston'), ('jizzax', 'Jizzax'), ('qashqadaryo', 'Qashqadaryo'), ('surxondaryo', 'Surxondaryo'), ('samarqand', 'Samarqand'), ('navoiy', 'Navoiy'), ('buxoro', 'Buxoro'), ('xorazm', 'Xorazm'), ('qaraqalpogiston', "Qaraqalpog'iston")], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
