# Generated by Django 3.1.14 on 2022-02-22 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0012_auto_20220222_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='qaysi_shahar_yoki_viloyat',
            new_name='qaysi_shahar_yoki_viloyat_yubormoqchisiz',
        ),
    ]
