# Generated by Django 3.1.14 on 2022-02-22 13:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0013_auto_20220222_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='qaysi_shahar_yoki_viloyat_yubormoqchisiz',
            field=models.CharField(choices=[('toshkent', 'Toshkent'), ('tashkent_city', 'Toshkent shahri'), ('vodiy', 'Vodiy'), ('toshkent_vodiy', 'Toshkent/Vodiy'), ('samarqand_toshkent', 'Toshkent/Samarqand'), ('namangan', 'Namangan'), ('andijan', 'Andijon'), ('fergana', "Farg'ona"), ('guliston', 'Guliston'), ('jizzax', 'Jizzax'), ('qashqadaryo', 'Qashqadaryo'), ('surxondaryo', 'Surxondaryo'), ('samarqand', 'Samarqand'), ('navoiy', 'Navoiy'), ('buxoro', 'Buxoro'), ('xorazm', 'Xorazm'), ('qaraqalpogiston', "Qaraqalpog'iston"), ('nordrhein_westfalen', 'Nordrhein Westfalen'), ('bayern', 'Bayern'), ('baden_weurttemberg', 'Baden Württemberg'), ('niedersachsen', 'Niedersachsen'), ('hessen', 'Hessen'), ('rheinland_pfalz', 'Rheinland Pfalz'), ('sachsen', 'Sachsen'), ('berlin', 'Berlin'), ('schleswig_holstein', 'Schleswig Holstein'), ('brandenburg', 'Brandenburg'), ('sachsen_anhalt', 'Sachsen-Anhalt'), ('thueringen', 'Thüringen'), ('hamburg', 'Hamburg'), ('mecklenburg_vorpommern', 'Mecklenburg-Vorpommern'), ('saarland', 'Saarland'), ('bremen', 'Bremen')], max_length=50),
        ),
    ]
