# Generated by Django 3.1.14 on 2022-02-28 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transfers', '0014_auto_20220222_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('transfer_comment', models.TextField(default='', max_length=150)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reply', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_replies', to='transfers.transfercomment')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_comments', to='transfers.transfer')),
            ],
        ),
    ]
