# Generated by Django 3.1.14 on 2022-03-01 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transfers', '0016_transfer_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='reputations',
            field=models.ManyToManyField(blank=True, related_name='reputations_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
