# Generated by Django 3.1.14 on 2022-03-03 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0017_transfer_reputations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='pul_yuboriladigan_davlatni_tanlang',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='transfer_pul_birligini_tanlang',
            new_name='moneyCurrency',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='transfer_turi',
            new_name='transferArt',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='qaysi_shahar_yoki_viloyat_yubormoqchisiz',
            new_name='whichLocation',
        ),
    ]
