# Generated by Django 3.1.14 on 2022-03-04 08:27

import ckeditor.fields
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0018_auto_20220303_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name="Transfer bo'yicha batafsil ma'lomot"),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='location',
            field=models.CharField(choices=[('UZB', "O'zbekistondan Germaniyaga"), ('GER', "Germaniyadan O'zbekistonga"), ('UZBUSA', "O'zbekistondan Amerikaga"), ('USAUZB', "Amerikadan O'zbekistonga")], max_length=100, verbose_name='Pul yuboriladigan davlatni tanlang'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='moneyCurrency',
            field=models.CharField(choices=[('dollar', 'faqat dollarda kerak'), ('som', 'faqat sömda kerak'), ('euro', 'faqat euroda kerak'), ('euroordollar', 'euro yoki dollarda kerak'), ('euroorsom', 'euro yoki sömda kerak'), ('somordollar', 'dollar yoki sömda kerak'), ('irrelevant', "farqi yo'q")], max_length=50, verbose_name='Transfer pul birligini tanlang'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='price',
            field=models.IntegerField(verbose_name='Transfer qilinadigan pul miqdori'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Transfer nomi'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transferArt',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('fasttransfer', 'Echtzeit Überweisung'), ('plastik', 'Plastik karta'), ('cash', 'Naqd pul'), ('paypal', 'Paypal'), ('normaltransfer', 'Bank hisob raqamidan (2-3 ish kuni davom etadi)'), ('irrelevant', "farqi yo'q")], default='fasttransfer', max_length=58, verbose_name='Transfer turi'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='whichLocation',
            field=models.CharField(choices=[('toshkent', 'Toshkent'), ('tashkent_city', 'Toshkent shahri'), ('vodiy', 'Vodiy'), ('toshkent_vodiy', 'Toshkent/Vodiy'), ('samarqand_toshkent', 'Toshkent/Samarqand'), ('namangan', 'Namangan'), ('andijan', 'Andijon'), ('fergana', "Farg'ona"), ('guliston', 'Guliston'), ('jizzax', 'Jizzax'), ('qashqadaryo', 'Qashqadaryo'), ('surxondaryo', 'Surxondaryo'), ('samarqand', 'Samarqand'), ('navoiy', 'Navoiy'), ('buxoro', 'Buxoro'), ('xorazm', 'Xorazm'), ('qaraqalpogiston', "Qaraqalpog'iston"), ('nordrhein_westfalen', 'Nordrhein Westfalen'), ('bayern', 'Bayern'), ('baden_weurttemberg', 'Baden Württemberg'), ('niedersachsen', 'Niedersachsen'), ('hessen', 'Hessen'), ('rheinland_pfalz', 'Rheinland Pfalz'), ('sachsen', 'Sachsen'), ('berlin', 'Berlin'), ('schleswig_holstein', 'Schleswig Holstein'), ('brandenburg', 'Brandenburg'), ('sachsen_anhalt', 'Sachsen-Anhalt'), ('thueringen', 'Thüringen'), ('hamburg', 'Hamburg'), ('mecklenburg_vorpommern', 'Mecklenburg-Vorpommern'), ('saarland', 'Saarland'), ('bremen', 'Bremen')], max_length=50, verbose_name='Qaysi shahar yoki viloyat/Bundesland ga yubormoqchisiz?'),
        ),
    ]
