# Generated by Django 3.1.14 on 2022-03-04 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transfers', '0019_auto_20220304_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='transfer_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
