# Generated by Django 3.1.14 on 2022-03-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0022_auto_20220304_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='exchangeRate',
            field=models.CharField(choices=[('google', 'Google kurs'), ('investing', 'Investing.com kurs')], default=0, max_length=50, verbose_name='Transfer qaysi kursda amalga oshiriladi?'),
            preserve_default=False,
        ),
    ]
