# Generated by Django 3.1.14 on 2022-03-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0024_auto_20220306_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='like_count',
            field=models.BigIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='whichLocation',
            field=models.CharField(choices=[('toshkent', 'Toshkent'), ('tashkent_city', 'Toshkent shahri'), ('vodiy', 'Vodiy'), ('toshkent_vodiy', 'Toshkent/Vodiy'), ('samarqand_toshkent', 'Toshkent/Samarqand'), ('namangan', 'Namangan'), ('andijan', 'Andijon'), ('fergana', "Farg'ona"), ('guliston', 'Guliston'), ('jizzax', 'Jizzax'), ('qashqadaryo', 'Qashqadaryo'), ('surxondaryo', 'Surxondaryo'), ('samarqand', 'Samarqand'), ('navoiy', 'Navoiy'), ('buxoro', 'Buxoro'), ('xorazm', 'Xorazm'), ('qaraqalpogiston', "Qaraqalpog'iston"), ('nordrhein_westfalen', 'Nordrhein Westfalen'), ('bayern', 'Bayern'), ('baden_weurttemberg', 'Baden Württemberg'), ('niedersachsen', 'Niedersachsen'), ('hessen', 'Hessen'), ('rheinland_pfalz', 'Rheinland Pfalz'), ('sachsen', 'Sachsen'), ('berlin', 'Berlin'), ('schleswig_holstein', 'Schleswig Holstein'), ('brandenburg', 'Brandenburg'), ('sachsen_anhalt', 'Sachsen-Anhalt'), ('thueringen', 'Thüringen'), ('hamburg', 'Hamburg'), ('mecklenburg_vorpommern', 'Mecklenburg-Vorpommern'), ('saarland', 'Saarland'), ('bremen', 'Bremen')], default='iltimos davlatni tanlang', max_length=50, verbose_name='Qaysi shahar yoki viloyat/Bundesland ga yubormoqchisiz?'),
        ),
    ]
