# Generated by Django 3.1.14 on 2022-03-13 19:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transfers', '0027_auto_20220313_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='views',
            field=models.ManyToManyField(blank=True, default=False, related_name='transfer_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
