# Generated by Django 3.1.14 on 2022-03-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0028_auto_20220313_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='job',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='subject',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='location',
            field=models.CharField(choices=[('Uzbekistan', 'Uzbekistan'), ('Germany', 'Germany')], max_length=50, verbose_name='Pul yuboriladigan davlatni tanlang'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='whichLocation',
            field=models.CharField(choices=[('Toshkent viloyati', 'Toshkent viloyati'), ("Farg'ona vodiysi", "Farg'ona vodiysi"), ('Samarqand', 'Samarqand'), ("Farg'ona", "Farg'ona"), ('Namangan', 'Namangan'), ('Andijon', 'Andijon'), ('Guliston', 'Guliston'), ('Jizzax', 'Jizzax'), ('Qashqadaryo', 'Qashqadaryo'), ('Surxondaryo', 'Surxondaryo'), ('Navoiy', 'Navoiy'), ('Xorazm', 'Xorazm'), ('Buxoro', 'Buxoro'), ("Qoraqalpog'iston", "Qoraqalpog'iston"), ('Stadt München', 'Stadt München'), ('Stadt Berlin', 'Stadt Berlin'), ('Stadt Hamburg', 'Stadt Hamburg'), ('Stadt Köln', 'Stadt Köln'), ('Stadt Frankfurt', 'Stadt Frankfurt'), ('Bayern', 'Bayern'), ('Baden Württemberg', 'Baden Württemberg'), ('Bremen', 'Bremen'), ('Brandenburg', 'Brandenburg'), ('Hessen', 'Hessen'), ('Mecklenburg-Vorpommern', 'Mecklenburg-Vorpommern'), ('Niedersachsen', 'Niedersachsen'), ('Nordrhein Westfalen', 'Nordrhein Westfalen'), ('Rheinland Pfalz', 'Rheinland Pfalz'), ('Sachsen', 'Sachsen'), ('Sachsen-Anhalt', 'Sachsen-Anhalt'), ('Saarland', 'Saarland'), ('Schleswig Holstein', 'Schleswig Holstein'), ('Thüringen', 'Thüringen')], max_length=50, verbose_name='Qaysi shahar yoki viloyat/Bundesland ga yubormoqchisiz'),
        ),
    ]
