# Generated by Django 3.1.14 on 2022-03-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0030_auto_20220323_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='status_transfer',
            field=models.BooleanField(default=True),
        ),
    ]
